### PR TITLE
Create documentation site with materials for mkdocs

### PR DESCRIPTION
**Pull request by enpuyou**
- Create documentation site with materials for Mkdocs
- Fix one function call bug in the main function

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @enpuyou can you explain a little further how this site is deployed? What would I need to do to deploy the site using, for instance, Netlify? Thanks for your work on this PR, it is awesome!

**Comment by enpuyou** [comment]
@gkapfham Yeah. I haven't really looked into the site deploying yet and I haven't tried to deploy a site for a while now, but I think there are a few ways to do it. I think the easiest way that I have come across yesterday is just to run a command like `mkdocs gh-deploy`, but this is for GitHub.io, and there probably is a way to do it with a custom domain name too. For netlify, just from some searches I just did, I think we need to include a `netlify.toml` file with some build scripts including like `mkdocs build`

**Comment by enpuyou** [comment]
The command to preview the site locally is through `mkdocs serve` or with the pipenv by `pipenv run mkdocs serve`

**Comment by gkapfham** [comment]
Hi @enpuyou, okay great, thanks for this update. It would be great if we could allow the deploys to happen automatically when someone updates the README file. Could you please link to any tutorials that you have read? That might help us as we work together as a team to get this deployed. thanks!

**Comment by enpuyou** [comment]
@gkapfham Some links I have seen so far: [deploying-your-docs](https://www.mkdocs.org/user-guide/deploying-your-docs/), [mkdocs-material-tutorial](https://medium.com/@ahmed.nafies/code-documentation-of-the-future-mkdocs-material-tutorial-35e5176d974f), [Official Documentation](https://squidfunk.github.io/mkdocs-material/getting-started/) (It doesn't talk too much about deploying, mostly just the configuration of the site)

**Comment by enpuyou** [comment]
@gkapfham https://docs.netlify.com/configure-builds/get-started/#basic-build-settings Seems like we just need to use the settings here to do continuous deployment or create a `netlify.toml` with more configurations

```
# MkDocs
If you're using MkDocs, make sure to specify the dependency in a requirements.txt file with mkdocs>=0.9.0. The typical build settings are as follows:

Build command: mkdocs build
Publish directory: site
```

**Pull request merged**
